    
# https://github.com/googlefonts/gftools/tree/main/docs/gftools-builder

    sources:
      - JetBrainsMono.glyphs
      - JetBrainsMono-Italic.glyphs
    axisOrder:
      - wght
      - ital
    familyName: JetBrains Mono
    logLevel: ERROR
    buildVariable: false
    buildStatic: true
    buildOTF: false
    buildTTF: true
    buildWebfont: false
    cleanUp: true