name: Build on Linux
run-name: Testing the build procedures on Linux
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Auto Update and Release"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Check for new release
      env:
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      shell: pwsh
      run: |
        if $(. "./Utils/check_if_updated_within_24H.ps1" ${{ secrets.GIT_USER_NAME }} JetBrainsMonoNerdFonts){
          Write-Host "The latest release is less than 24 hours old."
          Write-Host "Additional building tests will be cunducted."
          "should_ship_build_tests=false" | Out-File -FilePath $env:GITHUB_ENV -Append
        } else {
          Write-Host "The latest release is more than 24 hours old, or no release found."
          Write-Host "Additional building tests will be skipped."
          "should_ship_build_tests=true" | Out-File -FilePath $env:GITHUB_ENV -Append
        }
    - if: ${{ env.should_ship_build_tests == 'false' }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - name: Build
      if: ${{ env.should_ship_build_tests == 'false' }}
      shell: pwsh
      run: |
        sudo apt install fontforge
        pip install -r "./requirements.txt" -q
        . "./build.ps1"
